color = ''
project-name = 'default'
[default]
account_id = 'acct_1N2bSdSHWAEqZJFJ'
device_name = 'Gambhirs-MacBook-Air.local'
live_mode_api_key = 'rk_live_***********************************************************************************************2jrR'
live_mode_key_expires_at = '2023-07-29'
live_mode_pub_key = 'pk_live_51N2bSdSHWAEqZJFJqTR3ssosIPNsE1PHl9BjqmYmC8dwnHHXVtX0QO7x40CtOinMroIMh35mxEYf7wBNFENjYfJL00UDcQbXOx'
test_mode_api_key = 'rk_test_51N2bSdSHWAEqZJFJH2kj4PZjzkuQy0zoKo7OjCcFUEGUJs1baRTUaAj7CWL3uVFnQRyePcyIBvAThS5On4cug8to005PnLnC3i'
test_mode_key_expires_at = '2023-07-29'
test_mode_pub_key = 'pk_test_51N2bSdSHWAEqZJFJ1l7PGEet1WiyH4up9DYUcrWfsLvVUvGirRe3I8OL4H9oh6JwlFlyVUagZnhNv0EzfZKCKFnF00AKSkBa7K'

